module.exports = Object.freeze({
  SUCCESS: "Success",
  FAILURE: "Failure",
  HR: "hr",
  ADMIN: "admin",
  INTERVIEWER: "interviewer",
  MALE: "male",
  FEMALE: "female",
  INVALID_PAYLOAD: "Invalid Payload",
  USERNAME_ALREADY_EXIST: "Username already exists",
  EMAIL_ALREADY_EXIST: "Email ID already exists",
  EMAIL_DOES_NOT_EXIST: "Email ID does not exists",
  USER_REGISTERED_SUCCESSFULLY: "User Registered Successfully",
  CANDIDATE_ADDED_SUCCESSFULLY: "Candidate Added Successfully",
  CANDIDATE_UPDATED_SUCCESSFULLY: "Candidate Updated Successfully",
  EMAIL_DOES_NOT_EXIST_SIGN_UP: "Email Id does not exist, Sign-up to continue",
  INCORRECT_PASSWORD: "Incorrect Password",
  AUTHORIZATION: "Authorization",
  AUTHORIZED_SUCCESSFULLY: "Authorized successfully",
  INVALID_EMAIL_ID: "Invalid Email ID",
  USER_DELETED_SUCCESSFULLY: "User deleted successfully",
  CANDIDATE_DELETED_SUCCESSFULLY: "Candidate deleted successfully",
  INVALID_TYPE: "Invalid Type",
  INVALID_GENDER: "Invalid Gender",
  INVALID_TOKEN: "Invalid Token",
  AUTHORIZATION_FAILED: "Authorization Failed",
});
